sudo: required
services:
  - docker
before_install:
  - docker build -t baxhen/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true baxhen/react-test npm test
after_success:
  - docker build -t baxhen/dre-aws-multi-client ./client
  - docker build -t baxhen/dre-aws-multi-nginx ./nginx
  - docker build -t baxhen/dre-aws-multi-server ./server
  - docker build -t baxhen/dre-aws-multi-worker ./worker
  # Login in Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Images to Docker Hub
  - docker push baxhen/dre-aws-multi-client
  - docker push baxhen/dre-aws-multi-nginx
  - docker push baxhen/dre-aws-multi-server
  - docker push baxhen/dre-aws-multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: muilti-docker
  env: MuiltiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-209985839152
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
